title: Pronto
description: A web application that automates the phone helpdesk of the Campus of Cesena
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
